[package]
name = "meadowlark"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
edition = "2021"
license = "GPL-3.0"


[dependencies]
vizia = {git = "https://github.com/vizia/vizia", branch = "main"}
meadowlark-core-types = { git = "https://github.com/MeadowlarkDAW/meadowlark-core-types", branch = "main" }
dropseed = { git = "https://github.com/MeadowlarkDAW/dropseed.git", branch = "dev" }
#dropseed = { path = "../dropseed" }
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = { version = "0.4", default-features = false, features = ["std", "clock"]}
basedrop = "0.1"
crossbeam = "0.8"
rtrb = "0.2"
cpal = "0.13"
fnv = "1.0"
smallvec = "1.8"
rfd = "0.9"


# Enable this when we're ready to ship.
#[profile.release]
#lto = true

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 0
incremental = true